# SPDX-FileCopyrightText: Copyright 2022 EDF (Électricité de France S.A.)
# SPDX-License-Identifier: BSD-3-Clause
# See README for all details on copyright, authorship and license.

test:nightly:
  image: docker.io/rust
  script:
  - cargo version && cargo test --all --all-features
pages:
  image: docker.io/rust
  script:
    - cargo doc --no-deps
    - mkdir public
    - mv target/doc public/doc
  artifacts:
    paths:
      - public

reuse:
  image: python:3
  script:
    - pip install reuse
    - reuse lint
