[package]
name = "coap-gatt-utils"
version = "0.1.0"
edition = "2021"
authors = [ "EDF, developed in collaboration with Christian Amsüss" ]
license = "BSD-3-Clause"

[dependencies]
coap-message = "0.2.3"
coap-message-utils = "0.2.1"
heapless = "0.7.16"
